GET  http://localhost:3000/api/

### trigger error
GET  http://localhost:3000/api/throw

###
POST http://localhost:3000/api/hello
Content-Type: application/json

{
	"name":"Luigi"
}

### nested router
GET http://localhost:3000/api/nested/hello
Content-Type: application/json
