coverage:
  status:
    project:
      default:
        target: auto
      koa-api:
        target: auto
        flags:
          - koa-api

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

flags:
  koa-api:
    paths:
      - lib/koa-api/
    carryforward: true
