import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Koa API Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Koa API Demo</h1>

        <p className={styles.description}>
          Open browser developer tools and monitor the requests via network tab
        </p>
        <p>
          All requests are hitting one api route:{' '}
          <strong>pages/api/[[...hello]].ts</strong>
        </p>
        <div className={styles.grid}>
          <button className={styles.btn} onClick={() => fetch('api/hello')}>
            GET: api/hello
          </button>
          <button
            className={styles.btn}
            onClick={() => fetch('api/hello', { method: 'POST' })}
          >
            POST: api/hello
          </button>
          <button className={styles.btn} onClick={() => fetch('api/throw')}>
            Throw error: api/throw
          </button>
          <button
            className={styles.btn}
            onClick={() => fetch('api/nested/hello')}
          >
            Nested route: api/nested/hello
          </button>
        </div>
      </main>
    </div>
  )
}

export default Home
